PLANNED="PLANNED";ENTRY_SUBMITTING="ENTRY_SUBMITTING";HEDGED_PRIVATE_VERIFIED="HEDGED_PRIVATE_VERIFIED";OPEN="OPEN";EXIT_SUBMITTING="EXIT_SUBMITTING";CLOSED_PRIVATE_VERIFIED="CLOSED_PRIVATE_VERIFIED";FLATTEN_UNVERIFIED="FLATTEN_UNVERIFIED";UNKNOWN="UNKNOWN"
TERMINAL={CLOSED_PRIVATE_VERIFIED,"ABORTED"}
def can_advance(a,b):
 order=[PLANNED,ENTRY_SUBMITTING,HEDGED_PRIVATE_VERIFIED,OPEN,EXIT_SUBMITTING,CLOSED_PRIVATE_VERIFIED]
 return a in order and b in order and order.index(b)>=order.index(a)
