STATES=("SCANNED","VALIDATED","INTENTS_PERSISTED","SUBMITTED","HEDGED","EXITING","CLOSED_VERIFIED","HALTED")
def transition(current,new):
 allowed={"SCANNED":{"VALIDATED","HALTED"},"VALIDATED":{"INTENTS_PERSISTED","HALTED"},"INTENTS_PERSISTED":{"SUBMITTED","HALTED"},"SUBMITTED":{"HEDGED","HALTED"},"HEDGED":{"EXITING","HALTED"},"EXITING":{"CLOSED_VERIFIED","HALTED"}}
 return new if new in allowed.get(current,set()) else "HALTED"
